FROM maven:3.9-eclipse-temurin-19-alpine AS Build
WORKDIR /app
COPY src src
COPY pom.xml pom.xml
RUN mvn clean package

FROM eclipse-temurin:19-jre-alpine
WORKDIR /app
RUN addgroup -S mizg && adduser -S mizu -G mizg
USER mizu:mizg
COPY --from=Build /app/target/*.jar mizdooni.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "mizdooni.jar"]
